#!/bin/bash
set -x -e


cd /home/hadoop
sudo pip install virtualenv
mkdir IPythonNB
cd IPythonNB
/usr/local/bin/virtualenv -p /usr/bin/python2.7 venv
source venv/bin/activate

#Install ipython and dependency
pip install "ipython[notebook]"
pip install requests numpy
pip install matplotlib
pip install nltk
pip install boto3
pip install pdfminer

#Create profile 	
ipython profile create default

#Run on master /slave based on configuration

echo "c = get_config()" >  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.ip = '*'" >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.open_browser = False"  >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.port = 8192" >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py

#nohup ipython notebook --no-browser > /mnt/var/log/python_notebook.log &

#starting ipython notebook with pyspark interactive support.

export IPYTHON_HOME=/home/hadoop/IPythonNB/venv/
export PATH=$PATH:$IPYTHON_HOME/bin
export IPYTHON_OPTS="notebook --no-browser"
export MASTER=yarn-client

if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then

nohup /home/hadoop/spark/bin/pyspark --master yarn-client > /mnt/var/log/python_notebook.log &
 
fi

sudo pip install -U nltk
sudo mkdir /mnt1/py
sudo ln -s /mnt1/py /usr/share/nltk_data
sudo /usr/bin/python2.7 -m nltk.downloader -d /usr/share/nltk_data all


